# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverstatus',
            name='status',
            field=models.CharField(max_length=200),
        ),
    ]
